### ISSUE TITLE
runtime warning from numpy about invalid value in cast

### ISSUE THREAD

**Issue by JonathanGregory** [NCAS-CMS/cf-python#625]
There's an example field in the attached [zero.cdl.txt](https://github.com/NCAS-CMS/cf-python/files/11055193/zero.cdl.txt). The following produces the warning "/usr/share/anaconda3/lib/python3.8/site-packages/numpy/ma/core.py:467: RuntimeWarning: invalid value encountered in cast".

```

>>> cf.__version__
'3.14.1'
>>> numpy.__version__
'1.24.2'
n=cf.read('zero.nc')[0]
>>> n.dim('T').dump()
/usr/share/anaconda3/lib/python3.8/site-packages/numpy/ma/core.py:467: RuntimeWarning: invalid value encountered in cast
  fill_value = np.array(fill_value, copy=False, dtype=ndtype)
Dimension coordinate: time
    axis = 'T'
    calendar = '360_day'
    standard_name = 'time'
    units = 'days since 2007-1-1'
    Data(294) = [2007-01-01 00:00:00, ..., 2300-01-01 00:00:00] 360_day
```

**Comment by sadielbartholomew** [comment]
Hi @JonathanGregory, thanks for reporting this. I'll have a look into it whilst David is on leave.

I see you've included the cf and NumPy versions, but (if you get a chance), it may prove useful to know the whole set of dependency versions (as e.g. it might be something in `cfdm`), so please could you share the output also of running `cf.environment()` or `cf.environment(paths=False)` for the setup in which you see this. Thanks. Regardless I'll get back to you on this thread when I get a chance to investigate and know more.

**Comment by JonathanGregory** [comment]
Dear @sadielbartholomew 

Thanks. I have found that this does _not_ happen on a brand-new installation I have just made. So I expect it must be to do with a not-entirely consistent installation in which I have recently updated cf-python:

```
>>> cf.environment()
Platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.10 
HDF5 library: 1.12.0 
netcdf library: 4.7.4 
udunits2 library: libudunits2.so.0 
ESMF: not available 
Python: 3.8.5 /usr/share/anaconda3/bin/python
dask: 2023.3.1 /usr/share/anaconda3/lib/python3.8/site-packages/dask/__init__.py
netCDF4: 1.5.6 /usr/share/anaconda3/lib/python3.8/site-packages/netCDF4/__init__.py
psutil: 5.7.2 /usr/share/anaconda3/lib/python3.8/site-packages/psutil/__init__.py
packaging: 20.4 /usr/share/anaconda3/lib/python3.8/site-packages/packaging/__init__.py
numpy: 1.24.2 /usr/share/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
scipy: 1.5.2 /usr/share/anaconda3/lib/python3.8/site-packages/scipy/__init__.py
matplotlib: 3.3.2 /usr/share/anaconda3/lib/python3.8/site-packages/matplotlib/__init__.py
cftime: 1.6.2 /usr/share/anaconda3/lib/python3.8/site-packages/cftime/__init__.py
cfunits: 3.3.5 /usr/share/anaconda3/lib/python3.8/site-packages/cfunits/__init__.py
cfplot: 3.1.18 /usr/share/anaconda3/lib/python3.8/site-packages/cfplot/__init__.py
cfdm: 1.10.0.3 /usr/share/anaconda3/lib/python3.8/site-packages/cfdm/__init__.py
cf: 3.14.1 /usr/share/anaconda3/lib/python3.8/site-packages/cf/__init__.py
```

Best wishes

Jonathan

**Comment by sadielbartholomew** [comment]
Thanks for the further info, Jonathan. I'll take a look tomorrow and see if I can recreate the warning in some environment. Regardless I will report back soon.

**Comment by sadielbartholomew** [comment]
Hi again Jonathan, I haven't a chance this week to look into this after all, but in reviewing something else I did see the same warning arise in multiple places (and very repeatedly in those locations) on one of our test CI jobs, running with Linux OS (latest Ubuntu available) and Python 3.8, namely https://github.com/NCAS-CMS/cf-python/actions/runs/4551782556/jobs/8026279312?pr=627. This is further evidence of an environment which hits the warnings and it will help me to narrow down where in the cf-python or (cfdm) codebase the issue originates (as the tracebacks here obviously only point to the `numpy.ma` code location and the fault could get hit anywhere in the calls which show the warning). 

Anyway, I should be able to find time to resolve this early next week.

**Comment by sadielbartholomew** [comment]
With the updated numpy version, the warning is also appearing with `cfdm`, notably showing up for `test_example_field` (only) in the full test suite run there (and I can see that only `cfdm.example_field(4)` triggers it, one but not the only one of the `cfdm.example_fields()` with a `_FillValue` and of `-999.9`) so this might be emerging from `cfdm` rather than `cf`, else we need to adapt something in both codebases, separately, to prevent the warning coming through. I will try to fix the root cause(s) next week.

**Comment by sadielbartholomew** [comment]
Just as an update on this, I believe the warnings have been addressed somehow (inadvertently I believe) by one or both of the PRs NCAS-CMS/cfdm#255 (upstream) and its sibling here #630 in that they aren't showing in the test suites for branches that use those, which I noticed during my reviewing of each (which was a thorough rather than quick review).

I was due to get to the bottom of where the warnings were emerging from via `pdb` but I'll postpone that for now since the problem may have went away by itself during the extensive code changes as part of those PRs. We're doing a `cf` release next week so I'll double check we aren't seeing such warnings emerge from the woodwork before we do that release and close this accordingly when I am sure.

**Comment by JonathanGregory** [comment]
Dear @sadielbartholomew 

Sorry for slow reply. I have just tested it with my original example file and I still get the error :-(
```
>> cf.environment()
Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35 
HDF5 library: 1.12.2 
netcdf library: 4.9.3-development 
udunits2 library: libudunits2.so.0 
esmpy/ESMF: not available 
Python: 3.10.6 /usr/local/bin/python
dask: 2023.7.0 /usr/local/lib/python3.10/dist-packages/dask/__init__.py
netCDF4: 1.6.4 /usr/local/lib/python3.10/dist-packages/netCDF4/__init__.py
psutil: 5.9.0 /usr/lib/python3/dist-packages/psutil/__init__.py
packaging: 21.3 /usr/lib/python3/dist-packages/packaging/__init__.py
numpy: 1.25.1 /usr/local/lib/python3.10/dist-packages/numpy/__init__.py
scipy: 1.11.1 /usr/local/lib/python3.10/dist-packages/scipy/__init__.py
matplotlib: not available 
cftime: 1.6.2 /usr/local/lib/python3.10/dist-packages/cftime/__init__.py
cfunits: 3.3.6 /usr/local/lib/python3.10/dist-packages/cfunits/__init__.py
cfplot: not available 
cfdm: 1.10.1.0 /usr/local/lib/python3.10/dist-packages/cfdm/__init__.py
cf: 3.15.1 /usr/local/lib/python3.10/dist-packages/cf/__init__.py
>>> n=cf.read('../temp.nc')[0]
>>> n.dim('T').dump()
/usr/local/lib/python3.10/dist-packages/numpy/ma/core.py:467: RuntimeWarning: invalid value encountered in cast
  fill_value = np.array(fill_value, copy=False, dtype=ndtype)
Dimension coordinate: time
    axis = 'T'
    calendar = '360_day'
    standard_name = 'time'
    units = 'days since 2007-1-1'
    Data(294) = [2007-01-01 00:00:00, ..., 2300-01-01 00:00:00] 360_day
```
As you see, I have `cftime` 1.6.2, so it isn't the culprit for me, apparently.

Jonathan

**Comment by sadielbartholomew** [comment]
> I have just tested it with my original example file and I still get the error :-(

Ah, that's a shame since I thought I'd pinpointed the culprit :smiling_face_with_tear:. Sorry about that. No worries, I look over the traceback I reached in my previous comment and see if it leads me to the true culprit. I'll report back when I find out something more useful.

**Comment by sadielbartholomew** [comment]
Sorry @JonathanGregory, it is well overdue that we sort this, I am realising as I review NCAS-CMS/cfdm#292.

From some quick investigation after re-reading my report of previous deductions in this thread, I am fairly certain it relates to https://github.com/Unidata/cftime/issues/328. I will investigate and try to make the fix in cfdm after I submit my review to that PR.
